version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
    restart: always
    env_file:
      - api/.env-prod
    networks:
      - custom
    volumes:
      - db-command:/var/lib/postgresql/command

  db-init:
    image: postgres:15
    container_name: db_init
    depends_on:
      - db
    environment:
      PGPASSWORD: postgres
    networks:
      - custom
    command: >
      bash -c "
      sleep 5 &&
      psql -h db_app -U postgres -f /docker-entrypoint-initdb.d/init-db.sql
      "
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    env_file:
      - keycloak.env
    command: start-dev
    depends_on:
      - db
      - db-init
    networks:
      - custom
    restart: unless-stopped

  fastapi_app:
    env_file:
      - api/.env-prod
    build:
      context: api/
    # image: menoitami/task-tracker
    command: [ "/fastapi_app/docker/app.sh" ]
    expose:
      - 8000
    networks:
      - custom
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_app
    ports:
      - "80:80"     # HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Проброс nginx.conf
      - ./conf.d/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ./app/conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    depends_on:
      - fastapi_app
      - db
    networks:
      - custom

networks:
  custom:
    driver: bridge

volumes:
  db-data:
  minio-data:
  minio-config:
