version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
    restart: always
    env_file:
      - api/.env-prod
    networks:
      - custom
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6379
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - custom

  fastapi_app:
    env_file:
      - api/.env-prod
    build:
      context: api/
    # image: menoitami/task-tracker
    command: [ "/fastapi_app/docker/app.sh" ]
    expose:
      - 8000
    networks:
      - custom
    depends_on:
      - db
      - redis

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # Порт для S3-совместимого API
      - "9001:9001"  # Порт для веб-консоли MinIO
    environment:
      MINIO_ROOT_USER: myaccesskey  # Замените на ключ доступа длиной от 3 символов
      MINIO_ROOT_PASSWORD: mysecretpassword  # Замените на секретный ключ длиной от 8 символов
    volumes:
      - ./minio-data:/data  # Папка для хранения данных
      - ./minio-config:/root/.minio  # Папка для конфигурационных файлов
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - custom

  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set myminio http://minio:9000 myaccesskey mysecretpassword;
      mc mb myminio/users || true;
      mc policy set private myminio/dodiq
      "
    networks:
      - custom

  app:
    build: ./receipt_api
    expose:
      - "8080"
    env_file:
      - receipt_api/.env
    networks:
      - custom
    volumes:
      - ./receipt_api_logs:/app/logs  # Монтируем директорию для логов на хосте
    logging:
      driver: "json-file"
      options:
        max-size: "10m"         # Максимальный размер файла лога (например, 10 MB)
        max-file: "5"

  nginx:
    image: nginx:latest
    container_name: nginx_app
    ports:
      - "80:80"     # HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Проброс nginx.conf
      - ./conf.d/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ./app/conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    depends_on:
      - fastapi_app
      - db
      - redis
      - minio
      - app
    networks:
      - custom


networks:
  custom:
    driver: bridge

volumes:
  db-data:
  minio-data:
  minio-config:
