name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        env:
          HOST: "90.156.170.155"
          USER: "root"
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd DGTU-AUTUMN2024
            docker-compose down
            git pull
            docker-compose up --build -d
          EOF
